UNIT_INSIGHTS_EVALUATOR = "https://stock.cmcts.ai/c-agent/api/v1/prediction/5d624bf3-ee14-4d60-b29e-d970e2bb25e6"
SUMMARIZED_REPORT_EVALUATOR = "https://stock.cmcts.ai/c-agent/api/v1/prediction/a69824b6-79b7-44b7-8394-884122c56f85"